sudo: false
language: node_js
matrix:
  include:
    - node_js: 12
    - node_js: 10
    - node_js: 8
    - python: 2.7
      language: python
      before_script: pip install flake8
      script: flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
    - python: 3.7
      language: python
      dist: xenial    # required for Python 3.7 (travis-ci/travis-ci#9069)
      sudo: required  # required for Python 3.7 (travis-ci/travis-ci#9069)
      before_script: pip install flake8
      script: flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
before_install:
  - npm i -g npm
before_script:
  # Remove the './node_modules/.bin:' entry, see https://github.com/travis-ci/travis-ci/issues/8813
  - export PATH=`echo ${PATH} | sed -re 's,(^|:)(./)?node_modules/.bin($|:),\1,'`
  - npm install -g istanbul grunt-cli coveralls
  - npm install node-red
script:
  - istanbul cover grunt --report lcovonly && istanbul report text && ( cat coverage/lcov.info | $(npm get prefix)/bin/coveralls || true ) && rm -rf coverage
